version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Map container's port 80 to host's port 8080
    depends_on:
      - backend

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8181:8181"  # Map container's port 8000 to host's port 8181

# Remove volumes section as it's no longer needed
